### Creates a new patient entity
POST lb-1bd7dcdb.elb.localhost.localstack.cloud:4566/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "aws localstack Test",
  "email": "aws_test@example.com",
  "address": "123 main street22",
  "dateOfBirth": "1995-09-08",
  "registeredDate": "2024-11-28"
}

###