
PUT http://lb-1bd7dcdb.elb.localhost.localstack.cloud:4566/api/patients/e1b214b9-466f-434c-9ae8-d12f5791e808
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "aws localstack Test",
  "email": "aws_test@example.com",
  "address": "aws street",
  "dateOfBirth": "1995-09-08",
  "registeredDate": "2024-11-28"
}